package: vidstack
version: '1.3.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/vidstack
requires:
    redaxo: '^5.17.1'
    php:
        version: '>=8.2, <9'
conflicts:
    packages:
        plyr: '>0.0.1'
